global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API Gateway (Nginx)
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:80']
    metrics_path: '/nginx_status'
    scrape_interval: 10s
    honor_labels: true

  # Microservices - Product Service
  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:80']
    metrics_path: '/metrics'
    scrape_interval: 10s
    honor_labels: true

  # Microservices - Customer Service
  - job_name: 'customer-service'
    static_configs:
      - targets: ['customer-service:80']
    metrics_path: '/metrics'
    scrape_interval: 10s
    honor_labels: true

  # Microservices - Cart Service
  - job_name: 'cart-service'
    static_configs:
      - targets: ['cart-service:80']
    metrics_path: '/metrics'
    scrape_interval: 10s
    honor_labels: true

  # Microservices - Order Service
  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:80']
    metrics_path: '/metrics'
    scrape_interval: 10s
    honor_labels: true

  # Microservices - Stock Service
  - job_name: 'stock-service'
    static_configs:
      - targets: ['stock-service:80']
    metrics_path: '/metrics'
    scrape_interval: 10s
    honor_labels: true

  # Microservices - Sales Service
  - job_name: 'sales-service'
    static_configs:
      - targets: ['sales-service:80']
    metrics_path: '/metrics'
    scrape_interval: 10s
    honor_labels: true

  # Microservices - Reporting Service
  - job_name: 'reporting-service'
    static_configs:
      - targets: ['reporting-service:80']
    metrics_path: '/metrics'
    scrape_interval: 10s
    honor_labels: true

  # MongoDB metrics
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']
    scrape_interval: 30s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # Traefik metrics (if using Traefik)
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Health checks for all services
  - job_name: 'health-checks'
    static_configs:
      - targets: 
        - 'product-service:80'
        - 'customer-service:80'
        - 'cart-service:80'
        - 'order-service:80'
        - 'stock-service:80'
        - 'sales-service:80'
        - 'reporting-service:80'
        - 'api-gateway:80'
    metrics_path: '/health'
    scrape_interval: 30s
    honor_labels: true 