global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # ASP.NET Core applications
  - job_name: 'cornershop-apps'
    static_configs:
      - targets: ['app1:5000', 'app2:5000', 'app3:5000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Saga Orchestrator metrics
  - job_name: 'saga-orchestrator'
    static_configs:
      - targets: ['saga-orchestrator:80']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Microservices metrics
  - job_name: 'microservices'
    static_configs:
      - targets: 
        - 'order-service:80'
        - 'stock-service:80'
        - 'payment-service:80'
        - 'customer-service:80'
        - 'cart-service-1:80'
        - 'cart-service-2:80'
        - 'cart-service-3:80'
        - 'product-service:80'
        - 'sales-service:80'
        - 'reporting-service:80'
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Traefik metrics
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
    metrics_path: '/metrics'

  # MongoDB metrics (if using mongodb_exporter)
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']

  # Redis metrics (if using redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100'] 